spring:
  application:
    name: server

  messages:
    encoding: UTF-8


  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    #url: "jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:folia}"
    url: "jdbc:postgresql://${NEON_DATABASE}"
    username: "${POSTGRES_USER:folia}"
    password: "${POSTGRES_PASSWORD:folia}"

    # Connection Pool
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
      jdbc:
        lob:
          non_textual_creation: true
    show-sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration,classpath:db/dev-migration
    clean-disabled: false

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

jwt:
  secret: "${JWT_SECRET:dev-secret-change-me-please-change-me-please}"
  expiration: ${JWT_EXPIRATION:3600000}

application:
  cors:
    allowed-origins: "${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000,http://192.168.178.203:3000}"

logging:
    level:
        org.springframework: DEBUG

