spring:
  application:
    name: server

  messages:
    encoding: UTF-8

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true

  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    url: "jdbc:postgresql://${HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:folia}"
    username: "${POSTGRES_USER:folia}"
    password: "${POSTGRES_PASSWORD:folia}"

    # Connection Pool
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
      jdbc:
        lob:
          non_textual_creation: true
    show-sql: true

  flyway:
    enabled: false

application:
  security:
    jwt:
      secret-key: "${JWT_SECRET:KkweM4d/4pZ5+Jq0v5xG5yQ9XzB+F9hL2jN8p7s4r1o=}"
      expiration: ${JWT_EXPIRATION:86400000} # 1 day
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
