name: API Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgis:
        image: postgis/postgis:18-3.6
        env:
          POSTGRES_DB: folia
          POSTGRES_USER: folia
          POSTGRES_PASSWORD: folia
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Set up JDK 25 # For Spring Boot
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 25
          distribution: temurin

      - name: Build Spring Boot
        run: |
          cd server/ &&
          ./mvnw clean package -DskipTests

      - name: Wait for PostGIS
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U folia -d folia; then
              echo "PostGIS ready!"
              break
            fi
            sleep 1
          done    

      - name: Start Spring Boot Server
        run: |
          cd server/ &&
          nohup java -jar target/*.jar & sleep 30

      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 24

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Run Bruno Tests
        run: |
          cd tests/folia-api-tests/ &&
          bru run --env ci --reporter-html results.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v6.0.0
        with:
          name: bruno-test-results
          path: tests/folia-api-tests/results.html
